### PR TITLE
Fix dependency vulnerabilities

### PR DESCRIPTION
**Pull request by akreitals**
Update Lodash dependency version to fix vulnerability in Lodash 4.17.11. See https://app.snyk.io/vuln/SNYK-JS-LODASH-450202 for more information.

### CODE REVIEW

**Comment by akreitals** [comment]
Not sure why this build failed but if you point me in the right direction I'll fix this.

Be good to get this vulnerability resolved asap.

**Comment by akreitals** [comment]
Thanks @erdii. Whilst I understand that particular issue doesn't directly effect this package for those who have automated security vulnerability detection as part of their CI/CD pipeline it renders this package unusable.

Given a dependency change and a minor version bump should be a trivial task I am unsure why you would disregard this?

**Comment by akreitals** [comment]
Apologies I didn't notice that, I guess it does 👍 

Given that master has progressed and I need a branch to create a PR against are you suggesting we create a new branch at the 4.2.0 tag?

Not sure what your npm release process is but just let me know how you would like me to update this PR to best support that and I'm happy to make any changes.

**Comment by erdii** [comment]
I think you have to re-create the pull request from the new branch "4.x". 
I tried to edit this PR to say this "akreitals wants to merge 12 commits into mpneuried:4.x from akreitals:master" but then github tries to merge all master commits that were made in the meantime too.

Also if you don't mind losing "authorship" over the commit, I could replay your commit directly on the 4.x branch.

**Comment by akreitals** [comment]
Done, I don't mind about authorship so happy for you to accept or reject the other PR as long as the changes can be published.

**Pull request closed without merging**
