### PR TITLE
add a .has() method #131

### PR DESCRIPTION
**Pull request by regevbr**
add a .has() method #131

### CODE REVIEW

**Comment by regevbr** [comment]
@erdii can you please code review?
It seems that the changes you made to dependencies in https://github.com/mpneuried/nodecache/commit/b208726bdb9d49a6aabac543208556f2eedb57fc has messed up the npm install process on old node versions and I'm not sure how to solve it besides force upgrading npm to v3 in those tests

**Comment by erdii** [comment]
@regevbr yes there are breaking changes in the pipeline. we will be dropping support for node < 6.x (maybe even 6.x) in the next major release.
I should remove those old node versions from the tests... 😅

Code is nice and should work, but the call to `exists` (to check if the key already expired and was not cleaned up yet) is missing.

PS: CoffeeScript has an existential operator: instead of `x != null` you can write `x?`

**Comment by regevbr** [comment]
@erdii thanks! that is a good catch - I fixed the code and added tests to that use case.

About the deprecation, please keep support for node 6 as I'm stuck with it sadly and not in a position to upgrade.

**Comment by erdii** [comment]
@regevbr Ok I'll bring that up when we'll talk about compatibility! Thanks for your work here!

**Pull request merged**
